import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { Industry } from '../models/Industry.ts';
import { Role } from '../models/Role.ts';
import { roles } from './roles.ts';

dotenv.config();

const industries = [{
    slug: "web-development",
    name: "Web Development",
    subtitle: "Building what people see",
    color: "#D4845A",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    position: { x: 400, y: 300 },
    children: [
      {
        name: "Frontend",
        slug: "frontend",
        stacks: [
          { name: "HTML5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg", url: "https://developer.mozilla.org/docs/Web/HTML", category: "Core", dependencies: [] },
          { name: "CSS3", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg", url: "https://developer.mozilla.org/docs/Web/CSS", category: "Core", dependencies: ["HTML5"] },
          { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", url: "https://developer.mozilla.org/docs/Web/JavaScript", category: "Core", dependencies: ["HTML5","CSS3"] },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg", url: "https://typescriptlang.org", category: "Core", dependencies: ["JavaScript"] },
          { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", url: "https://react.dev", category: "Frameworks", dependencies: ["JavaScript","HTML5","CSS3"] },
          { name: "Vue", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg", url: "https://vuejs.org", category: "Frameworks", dependencies: ["JavaScript","HTML5","CSS3"] },
          { name: "Angular", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg", url: "https://angular.io", category: "Frameworks", dependencies: ["TypeScript","JavaScript","HTML5","CSS3"] },
          { name: "Svelte", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg", url: "https://svelte.dev", category: "Frameworks", dependencies: ["JavaScript","HTML5","CSS3"] },
          { name: "Next.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg", url: "https://nextjs.org", category: "Frameworks", dependencies: ["React","TypeScript","JavaScript","HTML5","CSS3"] },
          { name: "Nuxt", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuxtjs/nuxtjs-original.svg", url: "https://nuxt.com", category: "Frameworks", dependencies: ["Vue","JavaScript","HTML5","CSS3"] },
          { name: "Tailwind", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg", url: "https://tailwindcss.com", category: "Styling", dependencies: ["CSS3","HTML5"] },
          { name: "Sass", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg", url: "https://sass-lang.com", category: "Styling", dependencies: ["CSS3"] },
          { name: "Vite", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vite/vite-original.svg", url: "https://vitejs.dev", category: "Build Tools", dependencies: ["JavaScript"] },
          { name: "Webpack", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg", url: "https://webpack.js.org", category: "Build Tools", dependencies: ["JavaScript"] },
          { name: "Jest", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-original.svg", url: "https://jestjs.io", category: "Testing", dependencies: ["JavaScript"] },
          { name: "Playwright", icon: "https://playwright.dev/img/playwright-logo.svg", url: "https://playwright.dev", category: "Testing", dependencies: ["JavaScript"] },
          { name: "Cypress", icon: "https://www.cypress.io/images/favicon.ico", url: "https://cypress.io", category: "Testing", dependencies: ["JavaScript"] },
          { name: "PWA", icon: "https://web.dev/images/favicon.png", url: "https://web.dev/progressive-web-apps/", category: "Advanced Web", dependencies: ["JavaScript","HTML5","CSS3"] },
          { name: "WebSockets", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", url: "https://developer.mozilla.org/docs/Web/API/WebSockets_API", category: "Advanced Web", dependencies: ["JavaScript"] },
        ],
      },
      {
        name: "Backend",
        slug: "backend",
        stacks: [
          { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", url: "https://developer.mozilla.org/docs/Web/JavaScript", category: "Languages", dependencies: [] },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg", url: "https://typescriptlang.org", category: "Languages", dependencies: ["JavaScript"] },
          { name: "Python", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg", url: "https://python.org", category: "Languages", dependencies: [] },
          { name: "Java", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg", url: "https://dev.java", category: "Languages", dependencies: [] },
          { name: "Go", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg", url: "https://go.dev", category: "Languages", dependencies: [] },
          { name: "Rust", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg", url: "https://rust-lang.org", category: "Languages", dependencies: [] },
          { name: "C#", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg", url: "https://learn.microsoft.com/dotnet/csharp/", category: "Languages", dependencies: [] },
          { name: "Node.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg", url: "https://nodejs.org", category: "Runtimes", dependencies: ["JavaScript"] },
          { name: "Express", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg", url: "https://expressjs.com", category: "Frameworks", dependencies: ["Node.js","JavaScript","TypeScript"] },
          { name: "NestJS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nestjs/nestjs-original.svg", url: "https://nestjs.com", category: "Frameworks", dependencies: ["Node.js","TypeScript","JavaScript"] },
          { name: "FastAPI", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg", url: "https://fastapi.tiangolo.com", category: "Frameworks", dependencies: ["Python"] },
          { name: "Django", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg", url: "https://djangoproject.com", category: "Frameworks", dependencies: ["Python"] },
          { name: "Spring Boot", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg", url: "https://spring.io/projects/spring-boot", category: "Frameworks", dependencies: ["Java"] },
          { name: "PostgreSQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg", url: "https://postgresql.org", category: "Databases", dependencies: [] },
          { name: "MySQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg", url: "https://mysql.com", category: "Databases", dependencies: [] },
          { name: "MongoDB", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg", url: "https://mongodb.com", category: "Databases", dependencies: [] },
          { name: "Redis", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg", url: "https://redis.io", category: "Databases", dependencies: [] },
          { name: "REST", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg", url: "https://restfulapi.net", category: "APIs", dependencies: [] },
          { name: "GraphQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-original.svg", url: "https://graphql.org", category: "APIs", dependencies: [] },
          { name: "gRPC", icon: "https://grpc.io/img/favicon.ico", url: "https://grpc.io", category: "APIs", dependencies: [] },
          { name: "JWT", icon: "https://jwt.io/img/favicon/favicon-16x16.png", url: "https://jwt.io", category: "Security", dependencies: [] },
          { name: "OAuth2", icon: "https://oauth.net/images/oauth-logo-square.png", url: "https://oauth.net", category: "Security", dependencies: [] },
          { name: "Nginx", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nginx/nginx-original.svg", url: "https://nginx.org", category: "Infrastructure", dependencies: [] },
          { name: "Docker", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", url: "https://docker.com", category: "Infrastructure", dependencies: [] },
        ],
      },
    ],
  },
  {
    slug: "mobile-development",
    name: "Mobile Development",
    subtitle: "Apps in your pocket",
    color: "#B8956A",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg",
    position: { x: 750, y: 250 },
    children: [
      {
        name: "iOS",
        slug: "ios",
        stacks: [
          { name: "Swift", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg", url: "https://swift.org", category: "Language", dependencies: [] },
          { name: "Objective-C", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/objectivec/objectivec-original.svg", url: "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/", category: "Language", dependencies: [] },
          { name: "SwiftUI", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg", url: "https://developer.apple.com/xcode/swiftui/", category: "UI Frameworks", dependencies: ["Swift"] },
          { name: "UIKit", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg", url: "https://developer.apple.com/documentation/uikit", category: "UI Frameworks", dependencies: ["Swift"] },
          { name: "Core Data", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apple/apple-original.svg", url: "https://developer.apple.com/documentation/coredata", category: "Data & Storage", dependencies: ["Swift"] },
          { name: "SQLite", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg", url: "https://sqlite.org", category: "Data & Storage", dependencies: [] },
          { name: "Combine", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg", url: "https://developer.apple.com/documentation/combine", category: "State & Async", dependencies: ["Swift"] },
          { name: "Async/Await", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg", url: "https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html", category: "State & Async", dependencies: ["Swift"] },
          { name: "URLSession", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg", url: "https://developer.apple.com/documentation/foundation/urlsession", category: "Networking", dependencies: ["Swift"] },
          { name: "Alamofire", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg", url: "https://github.com/Alamofire/Alamofire", category: "Networking", dependencies: ["Swift","URLSession"] },
          { name: "CocoaPods", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cocoapods/cocoapods-original.svg", url: "https://cocoapods.org", category: "Package Managers", dependencies: [] },
          { name: "Swift PM", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg", url: "https://swift.org/package-manager/", category: "Package Managers", dependencies: ["Swift"] },
          { name: "Xcode", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xcode/xcode-original.svg", url: "https://developer.apple.com/xcode/", category: "Tooling", dependencies: [] },
          { name: "Fastlane", icon: "https://fastlane.tools/assets/img/fastlane-logo-web.png", url: "https://fastlane.tools", category: "Tooling", dependencies: [] },
          { name: "TestFlight", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apple/apple-original.svg", url: "https://developer.apple.com/testflight/", category: "Testing & CI", dependencies: ["Xcode"] },
          { name: "XCTest", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xcode/xcode-original.svg", url: "https://developer.apple.com/documentation/xctest", category: "Testing & CI", dependencies: ["Swift","Xcode"] },
        ],
      },
      {
        name: "Android",
        slug: "android",
        stacks: [
          { name: "Kotlin", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg", url: "https://kotlinlang.org", category: "Language", dependencies: [] },
          { name: "Java", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg", url: "https://dev.java", category: "Language", dependencies: [] },
          { name: "Jetpack Compose", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://developer.android.com/jetpack/compose", category: "UI Frameworks", dependencies: ["Kotlin"] },
          { name: "XML Layouts", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://developer.android.com/guide/topics/ui/declaring-layout", category: "UI Frameworks", dependencies: [] },
          { name: "Room", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://developer.android.com/training/data-storage/room", category: "Data & Storage", dependencies: ["Kotlin","SQLite"] },
          { name: "DataStore", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://developer.android.com/topic/libraries/architecture/datastore", category: "Data & Storage", dependencies: ["Kotlin","Coroutines"] },
          { name: "Coroutines", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg", url: "https://kotlinlang.org/docs/coroutines-overview.html", category: "Async & State", dependencies: ["Kotlin"] },
          { name: "Flow", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg", url: "https://kotlinlang.org/docs/flow.html", category: "Async & State", dependencies: ["Kotlin","Coroutines"] },
          { name: "ViewModel", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://developer.android.com/topic/libraries/architecture/viewmodel", category: "Async & State", dependencies: ["Kotlin"] },
          { name: "Retrofit", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://square.github.io/retrofit/", category: "Networking", dependencies: ["Kotlin","OkHttp"] },
          { name: "OkHttp", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://square.github.io/okhttp/", category: "Networking", dependencies: [] },
          { name: "Hilt", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://developer.android.com/training/dependency-injection/hilt-android", category: "DI", dependencies: ["Kotlin"] },
          { name: "Android Studio", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/androidstudio/androidstudio-original.svg", url: "https://developer.android.com/studio", category: "Tooling", dependencies: [] },
          { name: "Gradle", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gradle/gradle-original.svg", url: "https://gradle.org", category: "Tooling", dependencies: [] },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-original.svg", url: "https://firebase.google.com", category: "Backend Services", dependencies: [] },
          { name: "JUnit", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg", url: "https://junit.org", category: "Testing", dependencies: ["Kotlin","Java"] },
          { name: "Espresso", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://developer.android.com/training/testing/espresso", category: "Testing", dependencies: ["Kotlin"] },
        ],
      },
      {
        name: "Cross-Platform",
        slug: "cross-platform",
        stacks: [
          { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", url: "https://developer.mozilla.org/docs/Web/JavaScript", category: "Languages", dependencies: [] },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg", url: "https://typescriptlang.org", category: "Languages", dependencies: ["JavaScript"] },
          { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", url: "https://react.dev", category: "Frameworks", dependencies: ["TypeScript","JavaScript"] },
          { name: "React Native", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", url: "https://reactnative.dev", category: "Frameworks", dependencies: ["React","TypeScript","JavaScript"] },
          { name: "Flutter", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg", url: "https://flutter.dev", category: "Frameworks", dependencies: ["Dart"] },
          { name: "Expo", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", url: "https://expo.dev", category: "Frameworks", dependencies: ["React Native"] },
          { name: "Dart", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dart/dart-original.svg", url: "https://dart.dev", category: "Languages", dependencies: [] },
          { name: "Zustand", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", url: "https://zustand-demo.pmnd.rs", category: "State Management", dependencies: ["React"] },
          { name: "Redux", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg", url: "https://redux.js.org", category: "State Management", dependencies: ["React"] },
          { name: "Riverpod", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg", url: "https://riverpod.dev", category: "State Management", dependencies: ["Dart"] },
          { name: "React Navigation", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", url: "https://reactnavigation.org", category: "Navigation", dependencies: ["React Native"] },
          { name: "React Native TL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", url: "https://testing-library.com/docs/react-native-testing-library", category: "Testing", dependencies: ["React Native"] },
          { name: "Detox", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", url: "https://wix.github.io/Detox/", category: "Testing", dependencies: ["React Native"] },
          { name: "App Store", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apple/apple-original.svg", url: "https://developer.apple.com/app-store/", category: "Distribution", dependencies: [] },
          { name: "Play Store", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg", url: "https://play.google.com/console", category: "Distribution", dependencies: [] },
        ],
      },
    ],
  },
  {
    slug: "gaming",
    name: "Gaming",
    subtitle: "Building virtual worlds",
    color: "#7B8FA1",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg",
    position: { x: 200, y: 500 },
    children: [
      {
        name: "3D Engines",
        slug: "engines-3d",
        stacks: [
          { name: "Unity", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg", url: "https://unity.com", category: "Engines", dependencies: ["C#"] },
          { name: "Unreal Engine", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unrealengine/unrealengine-original.svg", url: "https://unrealengine.com", category: "Engines", dependencies: ["C++"] },
          { name: "Godot", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/godot/godot-original.svg", url: "https://godotengine.org", category: "Engines", dependencies: ["GDScript"] },
          { name: "C#", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg", url: "https://learn.microsoft.com/dotnet/csharp/", category: "Languages", dependencies: [] },
          { name: "C++", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", url: "https://isocpp.org", category: "Languages", dependencies: [] },
          { name: "GDScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/godot/godot-original.svg", url: "https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/", category: "Languages", dependencies: [] },
          { name: "Blender", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/blender/blender-original.svg", url: "https://blender.org", category: "3D & Assets", dependencies: [] },
          { name: "Shader Graph", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg", url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@latest", category: "3D & Assets", dependencies: ["Unity"] },
          { name: "Steam SDK", icon: "https://store.steampowered.com/favicon.ico", url: "https://partner.steamgames.com", category: "Publishing", dependencies: [] },
          { name: "PlayFab", icon: "https://playfab.com/wp-content/uploads/2016/05/favicon.png", url: "https://playfab.com", category: "Backend", dependencies: [] },
          { name: "Photon", icon: "https://www.photonengine.com/favicon.ico", url: "https://photonengine.com", category: "Multiplayer", dependencies: ["Unity","C#"] },
        ],
      },
      {
        name: "Game Logic",
        slug: "game-logic",
        stacks: [
          { name: "C++", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", url: "https://isocpp.org", category: "Languages", dependencies: [] },
          { name: "C#", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg", url: "https://learn.microsoft.com/dotnet/csharp/", category: "Languages", dependencies: [] },
          { name: "Data Structures", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", url: "https://en.cppreference.com/w/cpp/container", category: "Core Concepts", dependencies: [] },
          { name: "Algorithms", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", url: "https://en.cppreference.com/w/cpp/algorithm", category: "Core Concepts", dependencies: ["Data Structures"] },
          { name: "OOP Patterns", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", url: "https://gameprogrammingpatterns.com", category: "Design Patterns", dependencies: [] },
          { name: "Entity-Component", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg", url: "https://docs.unity3d.com/Packages/com.unity.entities@latest", category: "Design Patterns", dependencies: [] },
          { name: "Finite State Machine", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg", url: "https://gameprogrammingpatterns.com/state.html", category: "Design Patterns", dependencies: [] },
          { name: "Multithreading", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", url: "https://en.cppreference.com/w/cpp/thread", category: "Performance", dependencies: [] },
          { name: "Memory Management", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", url: "https://en.cppreference.com/w/cpp/memory", category: "Performance", dependencies: [] },
          { name: "CMake", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cmake/cmake-original.svg", url: "https://cmake.org", category: "Build", dependencies: [] },
          { name: "vcpkg", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", url: "https://vcpkg.io", category: "Build", dependencies: [] },
        ],
      },
    ],
  },
  {
    slug: "data-ai",
    name: "Data & AI",
    subtitle: "Turning data into decisions",
    color: "#A3B18A",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    position: { x: 600, y: 550 },
    children: [
      {
        name: "Machine Learning",
        slug: "machine-learning",
        stacks: [
          { name: "Python", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg", url: "https://python.org", category: "Languages", dependencies: [] },
          { name: "NumPy", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg", url: "https://numpy.org", category: "Core Libraries", dependencies: ["Python"] },
          { name: "Pandas", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg", url: "https://pandas.pydata.org", category: "Core Libraries", dependencies: ["Python","NumPy"] },
          { name: "scikit-learn", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scikitlearn/scikitlearn-original.svg", url: "https://scikit-learn.org", category: "ML Frameworks", dependencies: ["Python","NumPy"] },
          { name: "TensorFlow", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg", url: "https://tensorflow.org", category: "ML Frameworks", dependencies: ["Python"] },
          { name: "PyTorch", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg", url: "https://pytorch.org", category: "ML Frameworks", dependencies: ["Python"] },
          { name: "Keras", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/keras/keras-original.svg", url: "https://keras.io", category: "ML Frameworks", dependencies: ["TensorFlow"] },
          { name: "Hugging Face", icon: "https://huggingface.co/favicon.ico", url: "https://huggingface.co", category: "LLM & GenAI", dependencies: ["PyTorch"] },
          { name: "LangChain", icon: "https://langchain.com/favicon.ico", url: "https://langchain.com", category: "LLM & GenAI", dependencies: ["Python"] },
          { name: "OpenAI API", icon: "https://openai.com/favicon.ico", url: "https://platform.openai.com", category: "LLM & GenAI", dependencies: ["Python"] },
          { name: "MLflow", icon: "https://mlflow.org/favicon.ico", url: "https://mlflow.org", category: "MLOps", dependencies: ["Python"] },
          { name: "Weights & Biases", icon: "https://wandb.ai/favicon.ico", url: "https://wandb.ai", category: "MLOps", dependencies: ["Python"] },
          { name: "Docker", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", url: "https://docker.com", category: "MLOps", dependencies: [] },
          { name: "Jupyter", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jupyter/jupyter-original.svg", url: "https://jupyter.org", category: "Tooling", dependencies: ["Python"] },
          { name: "CUDA", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nvidia/nvidia-original.svg", url: "https://developer.nvidia.com/cuda-zone", category: "Compute", dependencies: [] },
        ],
      },
      {
        name: "Data Engineering",
        slug: "data-engineering",
        stacks: [
          { name: "Python", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg", url: "https://python.org", category: "Languages", dependencies: [] },
          { name: "SQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg", url: "https://www.w3schools.com/sql/", category: "Languages", dependencies: [] },
          { name: "Spark", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachespark/apachespark-original.svg", url: "https://spark.apache.org", category: "Processing", dependencies: ["Python","SQL"] },
          { name: "Kafka", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg", url: "https://kafka.apache.org", category: "Streaming", dependencies: [] },
          { name: "Airflow", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apacheairflow/apacheairflow-original.svg", url: "https://airflow.apache.org", category: "Orchestration", dependencies: ["Python"] },
          { name: "dbt", icon: "https://www.getdbt.com/favicon.ico", url: "https://getdbt.com", category: "Transformation", dependencies: ["SQL"] },
          { name: "Snowflake", icon: "https://www.snowflake.com/wp-content/themes/snowflake/favicon.ico", url: "https://snowflake.com", category: "Data Warehouse", dependencies: ["SQL"] },
          { name: "BigQuery", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg", url: "https://cloud.google.com/bigquery", category: "Data Warehouse", dependencies: ["SQL"] },
          { name: "Redshift", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/redshift/", category: "Data Warehouse", dependencies: ["SQL"] },
          { name: "Delta Lake", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachespark/apachespark-original.svg", url: "https://delta.io", category: "Storage Formats", dependencies: ["Spark"] },
          { name: "Parquet", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachespark/apachespark-original.svg", url: "https://parquet.apache.org", category: "Storage Formats", dependencies: [] },
          { name: "Great Expectations", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg", url: "https://greatexpectations.io", category: "Data Quality", dependencies: ["Python"] },
        ],
      },
    ],
  },
  {
    slug: "cybersecurity",
    name: "Cybersecurity",
    subtitle: "Protecting systems & data",
    color: "#6B7A8D",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
    position: { x: 950, y: 450 },
    children: [
      {
        name: "Offensive Security",
        slug: "offensive-security",
        stacks: [
          { name: "Kali Linux", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://kali.org", category: "Operating Systems", dependencies: [] },
          { name: "Nmap", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://nmap.org", category: "Reconnaissance", dependencies: [] },
          { name: "Shodan", icon: "https://shodan.io/favicon.ico", url: "https://shodan.io", category: "Reconnaissance", dependencies: [] },
          { name: "Metasploit", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://metasploit.com", category: "Exploitation", dependencies: [] },
          { name: "Burp Suite", icon: "https://portswigger.net/favicon.ico", url: "https://portswigger.net/burp", category: "Web Attacks", dependencies: [] },
          { name: "OWASP ZAP", icon: "https://owasp.org/favicon.ico", url: "https://zaproxy.org", category: "Web Attacks", dependencies: [] },
          { name: "SQLmap", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://sqlmap.org", category: "Web Attacks", dependencies: [] },
          { name: "Hashcat", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://hashcat.net", category: "Password Cracking", dependencies: [] },
          { name: "John the Ripper", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://openwall.com/john/", category: "Password Cracking", dependencies: [] },
          { name: "Wireshark", icon: "https://wireshark.org/favicon.ico", url: "https://wireshark.org", category: "Network Analysis", dependencies: [] },
          { name: "Python", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg", url: "https://python.org", category: "Scripting", dependencies: [] },
          { name: "Bash", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg", url: "https://gnu.org/software/bash/", category: "Scripting", dependencies: [] },
        ],
      },
      {
        name: "Defensive Security",
        slug: "defensive-security",
        stacks: [
          { name: "Splunk", icon: "https://splunk.com/favicon.ico", url: "https://splunk.com", category: "SIEM", dependencies: [] },
          { name: "Elastic SIEM", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elasticsearch/elasticsearch-original.svg", url: "https://elastic.co/security", category: "SIEM", dependencies: [] },
          { name: "Snort", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://snort.org", category: "IDS/IPS", dependencies: [] },
          { name: "Suricata", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://suricata.io", category: "IDS/IPS", dependencies: [] },
          { name: "Velociraptor", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://docs.velociraptor.app", category: "Threat Hunting", dependencies: [] },
          { name: "YARA", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://virustotal.github.io/yara/", category: "Threat Hunting", dependencies: [] },
          { name: "CrowdStrike", icon: "https://crowdstrike.com/favicon.ico", url: "https://crowdstrike.com", category: "EDR", dependencies: [] },
          { name: "Microsoft Defender", icon: "https://microsoft.com/favicon.ico", url: "https://microsoft.com/security", category: "EDR", dependencies: [] },
          { name: "Wireshark", icon: "https://wireshark.org/favicon.ico", url: "https://wireshark.org", category: "Forensics", dependencies: [] },
        ],
      },
    ],
  },
  {
    slug: "cloud-infrastructure",
    name: "Cloud & Infra",
    subtitle: "The invisible backbone",
    color: "#5B8C5A",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg",
    position: { x: 150, y: 200 },
    children: [
      {
        name: "Cloud Platforms",
        slug: "cloud-platforms",
        stacks: [
          { name: "AWS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com", category: "Platforms", dependencies: [] },
          { name: "Google Cloud", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg", url: "https://cloud.google.com", category: "Platforms", dependencies: [] },
          { name: "Azure", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg", url: "https://azure.microsoft.com", category: "Platforms", dependencies: [] },
          { name: "EC2", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/ec2/", category: "Compute", dependencies: ["AWS"] },
          { name: "Lambda", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/lambda/", category: "Compute", dependencies: ["AWS"] },
          { name: "Cloud Functions", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg", url: "https://cloud.google.com/functions", category: "Compute", dependencies: ["Google Cloud"] },
          { name: "S3", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/s3/", category: "Storage", dependencies: ["AWS"] },
          { name: "CloudFront", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/cloudfront/", category: "Networking", dependencies: ["AWS"] },
          { name: "Route 53", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/route53/", category: "Networking", dependencies: ["AWS"] },
          { name: "VPC", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/vpc/", category: "Networking", dependencies: ["AWS"] },
          { name: "RDS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/rds/", category: "Databases", dependencies: ["AWS"] },
          { name: "DynamoDB", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/dynamodb/", category: "Databases", dependencies: ["AWS"] },
          { name: "IAM", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/iam/", category: "Security", dependencies: ["AWS"] },
          { name: "SageMaker", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/sagemaker/", category: "AI/ML", dependencies: ["AWS"] },
        ],
      },
    ],
  },
  {
    slug: "devops",
    name: "DevOps",
    subtitle: "Ship faster, break less",
    color: "#C97B3D",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
    position: { x: 500, y: 100 },
    children: [
      {
        name: "Containers",
        slug: "containers",
        stacks: [
          { name: "Docker", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", url: "https://docker.com", category: "Containerization", dependencies: [] },
          { name: "Podman", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://podman.io", category: "Containerization", dependencies: [] },
          { name: "BuildKit", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", url: "https://docs.docker.com/buildx/working-with-buildx/", category: "Containerization", dependencies: ["Docker"] },
          { name: "Kubernetes", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-original.svg", url: "https://kubernetes.io", category: "Orchestration", dependencies: ["Docker"] },
          { name: "Helm", icon: "https://helm.sh/img/helm.svg", url: "https://helm.sh", category: "Orchestration", dependencies: ["Kubernetes"] },
          { name: "ArgoCD", icon: "https://argo-cd.readthedocs.io/en/stable/assets/favicon.ico", url: "https://argoproj.github.io/cd/", category: "Orchestration", dependencies: ["Kubernetes"] },
          { name: "Istio", icon: "https://istio.io/img/icons/istio-logo.svg", url: "https://istio.io", category: "Service Mesh", dependencies: ["Kubernetes"] },
          { name: "Linkerd", icon: "https://linkerd.io/favicon.ico", url: "https://linkerd.io", category: "Service Mesh", dependencies: ["Kubernetes"] },
          { name: "Docker Hub", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", url: "https://hub.docker.com", category: "Registries", dependencies: ["Docker"] },
          { name: "ECR", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/ecr/", category: "Registries", dependencies: ["Docker"] },
          { name: "GHCR", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg", url: "https://ghcr.io", category: "Registries", dependencies: ["Docker"] },
          { name: "Prometheus", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg", url: "https://prometheus.io", category: "Monitoring", dependencies: ["Kubernetes"] },
          { name: "Grafana", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg", url: "https://grafana.com", category: "Monitoring", dependencies: ["Prometheus"] },
          { name: "Trivy", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", url: "https://trivy.dev", category: "Security", dependencies: ["Docker"] },
        ],
      },
      {
        name: "CI/CD",
        slug: "ci-cd",
        stacks: [
          { name: "GitHub Actions", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg", url: "https://github.com/features/actions", category: "CI Platforms", dependencies: ["GitHub","Git"] },
          { name: "GitLab CI", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg", url: "https://docs.gitlab.com/ee/ci/", category: "CI Platforms", dependencies: ["GitLab","Git"] },
          { name: "CircleCI", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/circleci/circleci-original.svg", url: "https://circleci.com", category: "CI Platforms", dependencies: ["Git"] },
          { name: "Jenkins", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg", url: "https://jenkins.io", category: "CI Platforms", dependencies: ["Git"] },
          { name: "Buildkite", icon: "https://buildkite.com/favicon.ico", url: "https://buildkite.com", category: "CI Platforms", dependencies: ["Git"] },
          { name: "Git", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg", url: "https://git-scm.com", category: "Version Control", dependencies: [] },
          { name: "GitHub", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg", url: "https://github.com", category: "Version Control", dependencies: ["Git"] },
          { name: "GitLab", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg", url: "https://gitlab.com", category: "Version Control", dependencies: ["Git"] },
          { name: "Bitbucket", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bitbucket/bitbucket-original.svg", url: "https://bitbucket.org", category: "Version Control", dependencies: ["Git"] },
          { name: "Terraform", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg", url: "https://terraform.io", category: "Infrastructure as Code", dependencies: [] },
          { name: "Ansible", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg", url: "https://ansible.com", category: "Infrastructure as Code", dependencies: [] },
          { name: "Pulumi", icon: "https://pulumi.com/favicon.ico", url: "https://pulumi.com", category: "Infrastructure as Code", dependencies: [] },
          { name: "Docker", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", url: "https://docker.com", category: "Containerization", dependencies: [] },
          { name: "Kubernetes", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-original.svg", url: "https://kubernetes.io", category: "Containerization", dependencies: ["Docker"] },
          { name: "Helm", icon: "https://helm.sh/img/helm.svg", url: "https://helm.sh", category: "Containerization", dependencies: ["Kubernetes"] },
          { name: "Prometheus", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg", url: "https://prometheus.io", category: "Observability", dependencies: [] },
          { name: "Grafana", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg", url: "https://grafana.com", category: "Observability", dependencies: ["Prometheus"] },
          { name: "Datadog", icon: "https://datadoghq.com/favicon.ico", url: "https://datadoghq.com", category: "Observability", dependencies: [] },
          { name: "Docker Hub", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", url: "https://hub.docker.com", category: "Artifact Registries", dependencies: ["Docker"] },
          { name: "ECR", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg", url: "https://aws.amazon.com/ecr/", category: "Artifact Registries", dependencies: ["Docker"] },
        ],
      },
    ],
  },
  {
    slug: "embedded-systems",
    name: "Embedded Systems",
    subtitle: "Code meets hardware",
    color: "#8B6F47",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/arduino/arduino-original.svg",
    position: { x: 900, y: 150 },
    children: [
      {
        name: "Microcontrollers",
        slug: "microcontrollers",
        stacks: [
          { name: "Arduino", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/arduino/arduino-original.svg", url: "https://arduino.cc" },
          { name: "C", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg", url: "https://en.cppreference.com/w/c" },
        ],
      },
      {
        name: "IoT",
        slug: "iot",
        stacks: [
          { name: "Raspberry Pi", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/raspberrypi/raspberrypi-original.svg", url: "https://raspberrypi.org" },
          { name: "Python", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg", url: "https://python.org" },
        ],
      },
    ],
  },
];

async function runSeed() {
  await mongoose.connect(process.env.MONGODB_URI!);
  console.log('Connected to MongoDB for seeding...');

  await Industry.deleteMany({});
  await Role.deleteMany({});

  await Industry.insertMany(industries);
  await Role.insertMany(roles);

  console.log(`✅ Seeded ${industries.length} industries and ${roles.length} roles.`);
  mongoose.connection.close();
}

runSeed().catch(console.error);